version: '3'

tasks:
  run:
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yaml
  migration_up:
    cmds:
      - goose -dir migrations sqlite3 ./internal/storage/sso.db up
# go env -w CGO_ENABLED=1