version: '3'

tasks:
  run:
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yaml
  migration_up:
    cmds:
      - go run ./cmd/migrator --storage-path=./internal/storage/sso.db --migration-path=./migrations
  migration_up_test:
    cmds:
      - go run ./cmd/migrator --storage-path=./internal/storage/sso.db --migration-path=./tests/migration --migration-table=migrations_tests
# go env -w CGO_ENABLED=1