version: '3'

tasks:
  run:
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yaml
  migration_up:
    cmds:
      -  go run ./cmd/migrator --storage-path=./internal/storage/sso.db --migrations-path=./migrations --migrations-table=main
# go env -w CGO_ENABLED=1